### ISSUE TITLE
libvmaf with ffmpeg": No such filter: 'libvmaf'

### ISSUE THREAD

**Issue by ngcthuong** [Netflix/vmaf#547]
I got the above-mentioned issues with 

> [AVFilterGraph @ 0x4d6c700] No such filter: 'libvmaf'
> Error initializing complex filters.
> Invalid argument

My command is 

>  ffmpeg -f rawvideo -s:v 1920x1080 -r 120 -i rec2Beauty_1920x1080_120fps_420_8bit_YUV.yuv -f rawvideo -s:v 1920x1080 -r 120 -i Beauty_1920x1080_120fps_420_8bit_YUV.yuv -lavfi libvmaf="model_path=vmaf_v0.6.1.pkl:log_path=metrics.txt" -f null -

and my folder has

> Beauty_1920x1080_120fps_420_8bit_YUV.yuv  rec2Beauty_1920x1080_120fps_420_8bit_YUV.yuv  vmaf_v0.6.1.pkl

Any idea to fix this? 
Thank you
Thuong

**Comment by slhck** [comment]
Your ffmpeg was built without VMAF support. How did you install ffmpeg?

**Comment by ngcthuong** [comment]
Thank you for your feedback. I have build ffmpeg follow the [guideline](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

 Then I config ffmpeg with vmaf by the [official document
](https://ffmpeg.org/ffmpeg-filters.html#libvmaf)

which set the configure in the ffmpeg folder

> ./configure --enable-libvmaf --enable-version3

**Comment by ngcthuong** [comment]
However, when I just type 'ffmpeg" I could not see the option of libvmaf 

> ~/ffmpeg_sources/ffmpeg$ ffmpeg
ffmpeg version N-97301-gf1894c2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/home/canhnguyen/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/canhnguyen/ffmpeg_build/include --extra-ldflags=-L/home/canhnguyen/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/home/canhnguyen/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 78.102 / 58. 78.102
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.101 /  7. 77.101
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by kylophone** [comment]
Make sure you are calling the correct `ffmpeg` which you've just built.

`./configure --enable-libvmaf --enable-version3`

does not match with

`configuration: --prefix=/home/canhnguyen/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/canhnguyen/ffmpeg_build/include --extra-ldflags=-L/home/canhnguyen/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/home/canhnguyen/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree`

**Comment by ngcthuong** [comment]
I have fixed this problem. This problem caused by not recompile ffmeg after configuring with vmaf

**Comment by mobilejammer** [comment]
you say This problem caused by not recompile ffmeg after configuring with vmaf.however when i recompile this problem is existed also。Error applying option 'model_path' to filter 'libvmaf': Option not found

**Comment by nilfm** [comment]
Hi @mobilejammer, could you clarify what version of ffmpeg you are using? The `model_path` option was deprecated long ago and removed two months ago in [this commit](https://github.com/FFmpeg/FFmpeg/commit/6028728bb829c04cc68c66c846c75a70bf4c0613). The [documentation](https://ffmpeg.org/ffmpeg-filters.html#Examples-91) no longer shows it. Older versions still have access to this parameter.

To use a custom model, please follow the examples for the `model` option in the documentation linked above. For each model you want to use, you can supply `version`, `name`, `path`, `enable_transform`, and `disable_clip`. For example, the following command uses two models, each with a version and a custom name. Note the double backslash to escape the colons.
```
ffmpeg -i distorted.mpg -i reference.mpg -lavfi libvmaf='model=version=vmaf_v0.6.1\\:name=vmaf|version=vmaf_v0.6.1neg\\:name=vmaf_neg' -f null -
```
